### ISSUE TITLE
not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by praharshbhatt** [EikeSan/video-fall-detection#4]
```
Requriments:
numpy==1.14.5
opencv-python==4.1.2.30
pylint==1.9.2
scikit-learn==0.22.1
```

Error:
```
C:\Users\prahu\AppData\Local\Programs\Python\Python37\python.exe "D:\Apps\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 54257 --file "D:/Multiverse_Projects/Final year project- Fall Detection/video-fall-detection/new.py"
pydev debugger: process 19688 is connecting

Connected to pydev debugger (build 191.7479.30)
Traceback (most recent call last):
  File "D:\Apps\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "D:\Apps\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Apps\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Apps\JetBrains\PyCharm Community Edition 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Multiverse_Projects/Final year project- Fall Detection/video-fall-detection/new.py", line 19, in <module>
    _, contours, _ = cv2.findContours(fgmask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

Process finished with exit code 1

```

**Comment by praharshbhatt** [comment]
This works when using older versions of opencv.
Can you please update this project?

**Comment by afrozchakure** [comment]
I think the ``_, contours, _ `` needs to be replaced with ``contours, _``. I think it works after changing that.  @EikeSan
